on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mirkolenz' }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - if: ${{ github.event_name == 'schedule' }}
        run: |
          nix flake update --commit-lock-file --commit-lockfile-summary 'chore(deps): update flake.lock'
          git push
      - run: nix run .#manifest --impure
