on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mirkolenz' }}
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: DeterminateSystems/nix-installer-action@v6
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: nix run .#manifest --impure
