on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mirkolenz' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: DeterminateSystems/nix-installer-action@v7
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check --impure
      - run: nix run .#manifest --impure
        env:
          GH_TOKEN: ${{ github.token }}
